name: JavaScript Tests
on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Test the Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Debugging
      run: |
        node -v
        npm -v

    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "DIR=$(npm config get cache)" >> $GITHUB_OUTPUT
        echo "NPM_VERSION=$(npm -v)" >> $GITHUB_OUTPUT
        echo "NODE_VERSION=$(node -v)" >> $GITHUB_OUTPUT

    - name: Cache Dependencies
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.DIR }}
        key: ${{ runner.os }}-npm-${{ steps.npm-cache-dir.outputs.NODE_VERSION }}-${{ steps.npm-cache-dir.outputs.NPM_VERSION }}-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Run the build
      run: |
        npm run lint
        npm run build
