name: PHP Standards
on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: PHP Coding Standards
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none

    - name: Debugging
      run: |
        php --version
        php -m
        composer --version

    - name: Get Composer Cache Directory
      id: composer-cache-dir
      run: |
        echo "DIR=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache PHP Dependencies
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache-dir.outputs.DIR }}
        key: ${{ runner.os }}-composer-7.4-${{ hashFiles('composer.lock') }}

    - name: Install PHP Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: PHPCS cache
      uses: actions/cache@v4
      with:
        path: tests/cache
        key: ${{ runner.os }}-phpcs-7.4-${{ hashFiles('plugin.php') }}

    - name: Run the tests
      run: |
        composer test:phpcs
        composer test:phpstan
      env:
        MYSQL_DATABASE: wordpress
        WP_TESTS_DB_PASS: root
